//
//  AirTurnKeyCodes.h
//  AirTurnInterface
//
//  Created by Nick Brook on 03/09/2014.
//  Copyright (c) 2014 Nick Brook. All rights reserved.
//

#import <Foundation/Foundation.h>

/*!
 *  Constants defining AirTurn keyboard codes.  Commented out keys are not detected through AirTurnView
 */
typedef NS_ENUM(NSInteger, AirTurnKeyCode) {
    AirTurnKeyCodeUnknown = -1,
    AirTurnKeyCodeA = 0x04,
    AirTurnKeyCodeB = 0x05,
    AirTurnKeyCodeC = 0x06,
    AirTurnKeyCodeD = 0x07,
    AirTurnKeyCodeE = 0x08,
    AirTurnKeyCodeF = 0x09,
    AirTurnKeyCodeG = 0x0A,
    AirTurnKeyCodeH = 0x0B,
    AirTurnKeyCodeI = 0x0C,
    AirTurnKeyCodeJ = 0x0D,
    AirTurnKeyCodeK = 0x0E,
    AirTurnKeyCodeL = 0x0F,
    AirTurnKeyCodeM = 0x10,
    AirTurnKeyCodeN = 0x11,
    AirTurnKeyCodeO = 0x12,
    AirTurnKeyCodeP = 0x13,
    AirTurnKeyCodeQ = 0x14,
    AirTurnKeyCodeR = 0x15,
    AirTurnKeyCodeS = 0x16,
    AirTurnKeyCodeT = 0x17,
    AirTurnKeyCodeU = 0x18,
    AirTurnKeyCodeV = 0x19,
    AirTurnKeyCodeW = 0x1A,
    AirTurnKeyCodeX = 0x1B,
    AirTurnKeyCodeY = 0x1C,
    AirTurnKeyCodeZ = 0x1D,
    AirTurnKeyCode1 = 0x1E,
    AirTurnKeyCode2 = 0x1F,
    AirTurnKeyCode3 = 0x20,
    AirTurnKeyCode4 = 0x21,
    AirTurnKeyCode5 = 0x22,
    AirTurnKeyCode6 = 0x23,
    AirTurnKeyCode7 = 0x24,
    AirTurnKeyCode8 = 0x25,
    AirTurnKeyCode9 = 0x26,
    AirTurnKeyCode0 = 0x27,
    AirTurnKeyCodeBackslash = 0x31,
    AirTurnKeyCodeComma = 0x36,
    AirTurnKeyCodeEqual = 0x2E,
    AirTurnKeyCodeGrave = 0x35,
//    AirTurnKeyCodeKeypad1 = 0x59,
//    AirTurnKeyCodeKeypad2 = 0x5A,
//    AirTurnKeyCodeKeypad3 = 0x5B,
//    AirTurnKeyCodeKeypad4 = 0x5C,
//    AirTurnKeyCodeKeypad5 = 0x5D,
//    AirTurnKeyCodeKeypad6 = 0x5E,
//    AirTurnKeyCodeKeypad7 = 0x5F,
//    AirTurnKeyCodeKeypad8 = 0x60,
//    AirTurnKeyCodeKeypad9 = 0x61,
//    AirTurnKeyCodeKeypad0 = 0x62,
//    AirTurnKeyCodeKeypadClear = 0x53,
//    AirTurnKeyCodeKeypadDecimal = 0x63,
//    AirTurnKeyCodeKeypadDivide = 0x54,
//    AirTurnKeyCodeKeypadEnter = 0x58,
//    AirTurnKeyCodeKeypadEquals = 0x67,
//    AirTurnKeyCodeKeypadMinus = 0x56,
    AirTurnKeyCodeKeypadMultiply = 0x55,
    AirTurnKeyCodeKeypadPlus = 0x57,
    AirTurnKeyCodeLeftBracket = 0x2F,
    AirTurnKeyCodeRightBracket = 0x30,
    AirTurnKeyCodeMinus = 0x2D,
    AirTurnKeyCodePeriod = 0x37,
    AirTurnKeyCodeQuote = 0x34,
    AirTurnKeyCodeSemicolon = 0x33,
    AirTurnKeyCodeSlash = 0x38,
    AirTurnKeyCodeForwardDelete = 0x4C,
    AirTurnKeyCodeDelete = 0x2A,
    AirTurnKeyCodeUpArrow = 0x52,
    AirTurnKeyCodeRightArrow = 0x4F,
    AirTurnKeyCodeDownArrow = 0x51,
    AirTurnKeyCodeLeftArrow = 0x50,
//    AirTurnKeyCodeHome = 0x4A,
//    AirTurnKeyCodeEnd = 0x4D,
//    AirTurnKeyCodeEscape = 0x29,
//    AirTurnKeyCodeF1 = 0x3A,
//    AirTurnKeyCodeF2 = 0x3B,
//    AirTurnKeyCodeF3 = 0x3C,
//    AirTurnKeyCodeF4 = 0x3D,
//    AirTurnKeyCodeF5 = 0x3E,
//    AirTurnKeyCodeF6 = 0x3F,
//    AirTurnKeyCodeF7 = 0x40,
//    AirTurnKeyCodeF8 = 0x41,
//    AirTurnKeyCodeF9 = 0x42,
//    AirTurnKeyCodeF10 = 0x43,
//    AirTurnKeyCodeF11 = 0x44,
//    AirTurnKeyCodeF12 = 0x45,
//    AirTurnKeyCodeF13 = 0x68,
//    AirTurnKeyCodeF14 = 0x69,
//    AirTurnKeyCodeF15 = 0x6A,
//    AirTurnKeyCodeF16 = 0x6B,
//    AirTurnKeyCodeF17 = 0x6C,
//    AirTurnKeyCodeF18 = 0x6D,
//    AirTurnKeyCodeF19 = 0x6E,
//    AirTurnKeyCodeF20 = 0x6F,
    AirTurnKeyCodePageUp = 0x4B,
    AirTurnKeyCodePageDown = 0x4E,
    AirTurnKeyCodeReturn = 0x28,
    AirTurnKeyCodeSpace = 0x2C,
    AirTurnKeyCodeTab = 0x2B
};
